# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_soildata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='weather_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_main',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='weather_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
