# Generated by Django 6.0.3 on 2026-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_cropprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='rainfall',
            field=models.FloatField(default=200, help_text='Rainfall in mm'),
        ),
    ]
