# Generated by Django 6.0.6 on 2026-06-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_soildata_rainfall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='rainfall',
            field=models.FloatField(blank=True, default=200, help_text='Rainfall in mm'),
        ),
    ]
